# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/guillaume/Bureau/Project/GuardBits/GuardBits/GuardBits/src/ui/template/guard.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BitGuards(object):
    def setupUi(self, BitGuards):
        BitGuards.setObjectName("BitGuards")
        BitGuards.resize(795, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/mosaic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BitGuards.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(BitGuards)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.pbLogo = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLogo.sizePolicy().hasHeightForWidth())
        self.pbLogo.setSizePolicy(sizePolicy)
        self.pbLogo.setText("")
        self.pbLogo.setObjectName("pbLogo")
        self.gridLayout.addWidget(self.pbLogo, 0, 0, 1, 1)
        self.pbMenu = QtWidgets.QPushButton(self.frame)
        self.pbMenu.setText("")
        self.pbMenu.setObjectName("pbMenu")
        self.gridLayout.addWidget(self.pbMenu, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.centralLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 5))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 5))
        self.frame_2.setStyleSheet("background: qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 #e22026, stop:0.2 #593e75, stop:0.4 #2b64a4, stop:0.6 #0f849d, stop:0.8 #44bc94, stop:1 #e0d937); border:none; padding: 0px; margin:0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.centralLayout.addWidget(self.frame_2, 1, 0, 1, 3)
        self.ListMenu = QtWidgets.QListView(self.centralwidget)
        self.ListMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.ListMenu.setObjectName("ListMenu")
        self.centralLayout.addWidget(self.ListMenu, 2, 0, 1, 1)
        self.ListBits = QtWidgets.QListView(self.centralwidget)
        self.ListBits.setObjectName("ListBits")
        self.centralLayout.addWidget(self.ListBits, 2, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.centralLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.pbAdd = QtWidgets.QPushButton(self.centralwidget)
        self.pbAdd.setObjectName("pbAdd")
        self.centralLayout.addWidget(self.pbAdd, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(476, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.centralLayout.addItem(spacerItem2, 3, 2, 1, 1)
        BitGuards.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(BitGuards)
        self.statusBar.setObjectName("statusBar")
        BitGuards.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(BitGuards)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 795, 22))
        self.menuBar.setObjectName("menuBar")
        BitGuards.setMenuBar(self.menuBar)
        self.actionDefault = QtWidgets.QAction(BitGuards)
        self.actionDefault.setObjectName("actionDefault")
        self.actionDark = QtWidgets.QAction(BitGuards)
        self.actionDark.setObjectName("actionDark")
        self.actionNewSession = QtWidgets.QAction(BitGuards)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/diff-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewSession.setIcon(icon1)
        self.actionNewSession.setObjectName("actionNewSession")
        self.actionNewDataset = QtWidgets.QAction(BitGuards)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/data-array-large.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewDataset.setIcon(icon2)
        self.actionNewDataset.setObjectName("actionNewDataset")
        self.actionNewWorkFlow = QtWidgets.QAction(BitGuards)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/tree-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewWorkFlow.setIcon(icon3)
        self.actionNewWorkFlow.setObjectName("actionNewWorkFlow")
        self.actionViewControls = QtWidgets.QAction(BitGuards)
        self.actionViewControls.setObjectName("actionViewControls")
        self.actionViewKeywords = QtWidgets.QAction(BitGuards)
        self.actionViewKeywords.setObjectName("actionViewKeywords")
        self.actionViewInfo = QtWidgets.QAction(BitGuards)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/form.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewInfo.setIcon(icon4)
        self.actionViewInfo.setObjectName("actionViewInfo")
        self.actionAboutMOSAIC = QtWidgets.QAction(BitGuards)
        self.actionAboutMOSAIC.setIcon(icon)
        self.actionAboutMOSAIC.setObjectName("actionAboutMOSAIC")
        self.actionHelp = QtWidgets.QAction(BitGuards)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/help-view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionInput = QtWidgets.QAction(BitGuards)
        self.actionInput.setCheckable(True)
        self.actionInput.setChecked(True)
        self.actionInput.setIcon(icon3)
        self.actionInput.setText("")
        self.actionInput.setObjectName("actionInput")
        self.actionOutput = QtWidgets.QAction(BitGuards)
        self.actionOutput.setCheckable(True)
        self.actionOutput.setChecked(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/tree-load-g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOutput.setIcon(icon6)
        self.actionOutput.setText("")
        self.actionOutput.setObjectName("actionOutput")

        self.retranslateUi(BitGuards)
        QtCore.QMetaObject.connectSlotsByName(BitGuards)

    def retranslateUi(self, BitGuards):
        _translate = QtCore.QCoreApplication.translate
        BitGuards.setWindowTitle(_translate("BitGuards", "BitGuards"))
        self.pbAdd.setText(_translate("BitGuards", "PushButton"))
        self.actionDefault.setText(_translate("BitGuards", "Default"))
        self.actionDark.setText(_translate("BitGuards", "Dark"))
        self.actionNewSession.setText(_translate("BitGuards", "New Session"))
        self.actionNewSession.setShortcut(_translate("BitGuards", "Ctrl+S"))
        self.actionNewDataset.setText(_translate("BitGuards", "New Dataset"))
        self.actionNewDataset.setShortcut(_translate("BitGuards", "Ctrl+D"))
        self.actionNewWorkFlow.setText(_translate("BitGuards", "New WorkFlow"))
        self.actionNewWorkFlow.setShortcut(_translate("BitGuards", "Ctrl+W"))
        self.actionViewControls.setText(_translate("BitGuards", "View Controls"))
        self.actionViewControls.setShortcut(_translate("BitGuards", "Alt+C"))
        self.actionViewKeywords.setText(_translate("BitGuards", "View Keywords"))
        self.actionViewKeywords.setShortcut(_translate("BitGuards", "Alt+K"))
        self.actionViewInfo.setText(_translate("BitGuards", "View Info"))
        self.actionViewInfo.setShortcut(_translate("BitGuards", "Alt+I"))
        self.actionAboutMOSAIC.setText(_translate("BitGuards", "About MOSAIC"))
        self.actionHelp.setText(_translate("BitGuards", "Help"))
        self.actionInput.setToolTip(_translate("BitGuards", "Activate or deactivate the input dock"))
        self.actionInput.setShortcut(_translate("BitGuards", "Ctrl+I"))
        self.actionOutput.setToolTip(_translate("BitGuards", "Activate or deactivate the output dock"))
        self.actionOutput.setShortcut(_translate("BitGuards", "Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BitGuards = QtWidgets.QMainWindow()
    ui = Ui_BitGuards()
    ui.setupUi(BitGuards)
    BitGuards.show()
    sys.exit(app.exec_())
