# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/guillaume/Bureau/Project/GuardBits/GuardBits/GuardBits/src/ui/template/login.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(795, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/mosaic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.centralLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.loginWidget = QtWidgets.QWidget(self.centralwidget)
        self.loginWidget.setMinimumSize(QtCore.QSize(300, 200))
        self.loginWidget.setBaseSize(QtCore.QSize(0, 0))
        self.loginWidget.setObjectName("loginWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.loginWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labDesc = QtWidgets.QLabel(self.loginWidget)
        self.labDesc.setObjectName("labDesc")
        self.gridLayout.addWidget(self.labDesc, 2, 1, 1, 1)
        self.lePassword = QtWidgets.QLineEdit(self.loginWidget)
        self.lePassword.setObjectName("lePassword")
        self.gridLayout.addWidget(self.lePassword, 4, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labLogo = QtWidgets.QLabel(self.loginWidget)
        self.labLogo.setObjectName("labLogo")
        self.horizontalLayout_2.addWidget(self.labLogo)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnLogin = QtWidgets.QPushButton(self.loginWidget)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 8, 0, 1, 3)
        self.leLogin = QtWidgets.QLineEdit(self.loginWidget)
        self.leLogin.setObjectName("leLogin")
        self.gridLayout.addWidget(self.leLogin, 3, 1, 1, 1)
        self.centralLayout.addWidget(self.loginWidget, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.centralLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.centralLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.centralLayout.addItem(spacerItem5, 0, 1, 1, 1)
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(LoginWindow)
        self.statusBar.setObjectName("statusBar")
        LoginWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(LoginWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 795, 22))
        self.menuBar.setObjectName("menuBar")
        LoginWindow.setMenuBar(self.menuBar)
        self.actionDefault = QtWidgets.QAction(LoginWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionDark = QtWidgets.QAction(LoginWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionNewSession = QtWidgets.QAction(LoginWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/diff-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewSession.setIcon(icon1)
        self.actionNewSession.setObjectName("actionNewSession")
        self.actionNewDataset = QtWidgets.QAction(LoginWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/data-array-large.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewDataset.setIcon(icon2)
        self.actionNewDataset.setObjectName("actionNewDataset")
        self.actionNewWorkFlow = QtWidgets.QAction(LoginWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/tree-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewWorkFlow.setIcon(icon3)
        self.actionNewWorkFlow.setObjectName("actionNewWorkFlow")
        self.actionViewControls = QtWidgets.QAction(LoginWindow)
        self.actionViewControls.setObjectName("actionViewControls")
        self.actionViewKeywords = QtWidgets.QAction(LoginWindow)
        self.actionViewKeywords.setObjectName("actionViewKeywords")
        self.actionViewInfo = QtWidgets.QAction(LoginWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/icons/form.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionViewInfo.setIcon(icon4)
        self.actionViewInfo.setObjectName("actionViewInfo")
        self.actionAboutMOSAIC = QtWidgets.QAction(LoginWindow)
        self.actionAboutMOSAIC.setIcon(icon)
        self.actionAboutMOSAIC.setObjectName("actionAboutMOSAIC")
        self.actionHelp = QtWidgets.QAction(LoginWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/icons/help-view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.actionInput = QtWidgets.QAction(LoginWindow)
        self.actionInput.setCheckable(True)
        self.actionInput.setChecked(True)
        self.actionInput.setIcon(icon3)
        self.actionInput.setText("")
        self.actionInput.setObjectName("actionInput")
        self.actionOutput = QtWidgets.QAction(LoginWindow)
        self.actionOutput.setCheckable(True)
        self.actionOutput.setChecked(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/icons/tree-load-g.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOutput.setIcon(icon6)
        self.actionOutput.setText("")
        self.actionOutput.setObjectName("actionOutput")

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "BitGuards"))
        self.labDesc.setText(_translate("LoginWindow", "Identifiez vous sur votre compte BitGuards"))
        self.labLogo.setText(_translate("LoginWindow", "Logo"))
        self.btnLogin.setText(_translate("LoginWindow", "Connexion"))
        self.actionDefault.setText(_translate("LoginWindow", "Default"))
        self.actionDark.setText(_translate("LoginWindow", "Dark"))
        self.actionNewSession.setText(_translate("LoginWindow", "New Session"))
        self.actionNewSession.setShortcut(_translate("LoginWindow", "Ctrl+S"))
        self.actionNewDataset.setText(_translate("LoginWindow", "New Dataset"))
        self.actionNewDataset.setShortcut(_translate("LoginWindow", "Ctrl+D"))
        self.actionNewWorkFlow.setText(_translate("LoginWindow", "New WorkFlow"))
        self.actionNewWorkFlow.setShortcut(_translate("LoginWindow", "Ctrl+W"))
        self.actionViewControls.setText(_translate("LoginWindow", "View Controls"))
        self.actionViewControls.setShortcut(_translate("LoginWindow", "Alt+C"))
        self.actionViewKeywords.setText(_translate("LoginWindow", "View Keywords"))
        self.actionViewKeywords.setShortcut(_translate("LoginWindow", "Alt+K"))
        self.actionViewInfo.setText(_translate("LoginWindow", "View Info"))
        self.actionViewInfo.setShortcut(_translate("LoginWindow", "Alt+I"))
        self.actionAboutMOSAIC.setText(_translate("LoginWindow", "About MOSAIC"))
        self.actionHelp.setText(_translate("LoginWindow", "Help"))
        self.actionInput.setToolTip(_translate("LoginWindow", "Activate or deactivate the input dock"))
        self.actionInput.setShortcut(_translate("LoginWindow", "Ctrl+I"))
        self.actionOutput.setToolTip(_translate("LoginWindow", "Activate or deactivate the output dock"))
        self.actionOutput.setShortcut(_translate("LoginWindow", "Ctrl+O"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec_())
